### ISSUE TITLE
Cannot remove a VPN that is not assigned to 'admin' priviledges

### ISSUE THREAD

**Issue by Tommy1231232** [dappnode/DAppNode#302]
Within the VPN tab of my.dappnode, I have two VPNs. One of which is the admin and the other that is not (per the green slider). I try to remove the name that is not tagged to 'Admin" (by clicking the trashbin icon) and I receive the following error:

Error: Cannot remove the main admin user
    at /usr/src/app/src/calls/removeDevice.ts:14:11
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/src/calls/removeDevice.js:5:58)
Error: Cannot remove the main admin user
    at Object.<anonymous> (/usr/src/app/webpack:/admin-ui/src/common/transport/jsonRpc/index.ts:91:19)
    at Generator.next (<anonymous>)
    at /usr/src/app/index.js:123531:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/index.js:123527:12)
    at Object.parseRpcResponse (/usr/src/app/index.js:123616:12)
    at /usr/src/app/webpack:/src/api/vpnApiClient.ts:69:10
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/index.js:102865:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

{
  "id": "dappnode_admin"
}

It would be great if I could remove this other VPN that is not tagged to admin.

**Comment by pablomendezroyo** [comment]
> Within the VPN tab of my.dappnode, I have two VPNs. One of which is the admin and the other that is not (per the green slider). I try to remove the name that is not tagged to 'Admin" (by clicking the trashbin icon) and I receive the following error:
> 
> Error: Cannot remove the main admin user
> at /usr/src/app/src/calls/removeDevice.ts:14:11
> at Generator.next ()
> at fulfilled (/usr/src/app/src/calls/removeDevice.js:5:58)
> Error: Cannot remove the main admin user
> at Object. (/usr/src/app/webpack:/admin-ui/src/common/transport/jsonRpc/index.ts:91:19)
> at Generator.next ()
> at /usr/src/app/index.js:123531:71
> at new Promise ()
> at __awaiter (/usr/src/app/index.js:123527:12)
> at Object.parseRpcResponse (/usr/src/app/index.js:123616:12)
> at /usr/src/app/webpack:/src/api/vpnApiClient.ts:69:10
> at Generator.next ()
> at fulfilled (/usr/src/app/index.js:102865:58)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 
> {
> "id": "dappnode_admin"
> }
> 
> It would be great if I could remove this other VPN that is not tagged to admin as this is a security issue

Hi there!

Thank you for your suggestion, I think is not a security issue to have always an admin user because:
- If you want to change the credentials of the admin, click on "reset" and this will re-generate the admin_credentials
- If you do not want to have the VPN service, click on "stop" package and this  will stop the service of your vpn

**Comment by Tommy1231232** [comment]
@pablomendezroyo I am not trying to delete the VPN that is tagged to "admin". I am trying to delete the other VPN that is not assigned to admin. See below. How do you navigate to "stop"?


![Screen Shot 2021-06-17 at 8 29 37 AM](https://user-images.githubusercontent.com/71620056/122396641-304dd680-cf46-11eb-9d95-c1d2a69702ce.png)

**Comment by Tommy1231232** [comment]
@pablomendezroyo any update here?
