### ISSUE TITLE
Error on host update: Command failed: docker run

### ISSUE THREAD

**Issue by ligi** [dappnode/DAppNode#414]
I tried to do the host update on my dappnode and see this:

```
Error on host update: Command failed: docker run --rm --privileged --pid=host -t alpine:3.8 nsenter -t 1 -m -u -n -i /bin/bash /usr/src/dappnode/DNCORE/scripts/host/host_update.sh
Error: Error on host update: Command failed: docker run --rm --privileged --pid=host -t alpine:3.8 nsenter -t 1 -m -u -n -i /bin/bash /usr/src/dappnode/DNCORE/scripts/host/host_update.sh 

    at /usr/src/app/webpack:/@dappnode/dappmanager/src/utils/shell.ts:35:16
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/index.js:274817:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Error on host update: Command failed: docker run --rm --privileged --pid=host -t alpine:3.8 nsenter -t 1 -m -u -n -i /bin/bash /usr/src/dappnode/DNCORE/scripts/host/host_update.sh 

    at http://my.dappnode/static/js/main.17fcdcc7.js:2:10025
    at l (http://my.dappnode/static/js/main.17fcdcc7.js:2:541368)
    at Generator._invoke (http://my.dappnode/static/js/main.17fcdcc7.js:2:541156)
    at Generator.next (http://my.dappnode/static/js/main.17fcdcc7.js:2:541797)
    at r (http://my.dappnode/static/js/main.17fcdcc7.js:2:688019)
    at s (http://my.dappnode/static/js/main.17fcdcc7.js:2:688222)
    at http://my.dappnode/static/js/main.17fcdcc7.js:2:688281
    at new Promise (<anonymous>)
    at http://my.dappnode/static/js/main.17fcdcc7.js:2:688162
    at p (http://my.dappnode/static/js/main.17fcdcc7.js:2:9842)
```

![image](https://user-images.githubusercontent.com/111600/159658620-31817830-2f33-49c9-b664-3f898090a714.png)

System info:

*Before filing a new topic, please **provide the following information**.*

## Core DAppNode Packages versions
- **bind.dnp.dappnode.eth**: 0.2.6
- **core.dnp.dappnode.eth**: 0.2.52
- **dappmanager.dnp.dappnode.eth**: 0.2.47, commit: 35c4a081
- **https.dnp.dappnode.eth**: 0.1.3
- **ipfs.dnp.dappnode.eth**: 0.2.15
- **vpn.dnp.dappnode.eth**: 0.2.8, commit: f9a8743e
- **wifi.dnp.dappnode.eth**: 0.2.8
- **wireguard.dnp.dappnode.eth**: 0.1.1

## System info
- **dockerComposeVersion**: 1.25.5
- **dockerServerVersion**: 19.03.8
- **dockerCliVersion**: 19.03.8
- **os**: debian
- **versionCodename**: buster
- **architecture**: amd64
- **kernel**: 4.19.0-9-amd64
- **Disk usage**: 85%

**Comment by pablomendezroyo** [comment]
@ligi thanks for the report!

There are logs in a file that should bring us some important information about what happened, the inconvenient is that we do not provide yet through the UI so you will have to check them through the CLI.

To display the logs execute the following command in the dappnode host terminal:
```
cat /usr/src/dappnode/logs/update.log
```

**Comment by ligi** [comment]
thanks - have not sshed into my dappnode for a long time ;-)
And just tried it and get Permission denied - it should be the same username/password combination that I log in with through the UI right?

**Comment by pablomendezroyo** [comment]
yes! but I'm not sure about the port, I think it is 1337. Any way you could check the ssh config at http://my.dappnode/#/system/advanced

The command will look something like
```
ssh dappnode@XXX.XXX.XXX.XXX   -p 1337    
```

**Comment by ligi** [comment]
hm - the port is 22 - I can ssh - but I get permission denied with the credentials I usually use to login to the dappnode

**Comment by alexpeterson91** [comment]
> hm - the port is 22 - I can ssh - but I get permission denied with the credentials I usually use to login to the dappnode

I think pablo misspoke, the credentials are different for the host password and the admin UI.  have you tried the default password `dappnode.s0` ?

**Comment by alexpeterson91** [comment]
That’s expected the host password and the admin UI password are different. Have you tried the default password `dappnode.s0` ?
