### ISSUE TITLE
Can't expose Nethermind via HTTPS: "No container found for nethermind.public.dappnode.eth nethermind.public.dappnode.eth"

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#449]
When trying to expose my Eth1 node to the outside, an error pops up, preventing me from exposing the RPC endpoint.

<img width="258" alt="Screenshot 2022-06-09 at 14 42 50" src="https://user-images.githubusercontent.com/19168735/172850003-993bb44d-6709-47ea-879c-ef57ef0e8006.png">

Logs show:

```
Error: No container found for nethermind.public.dappnode.eth nethermind.public.dappnode.eth
    at HttpsPortal.<anonymous> (/usr/src/app/webpack:/@dappnode/dappmanager/src/modules/https-portal/index.ts:178:13)
    at Generator.next (<anonymous>)
    at /usr/src/app/index.js:265406:71
    at new Promise (<anonymous>)
    at __webpack_modules__.70910.__awaiter (/usr/src/app/index.js:265402:12)
    at HttpsPortal.getContainerForMapping (/usr/src/app/index.js:265548:16)
    at HttpsPortal.<anonymous> (/usr/src/app/webpack:/@dappnode/dappmanager/src/modules/https-portal/index.ts:32:34)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/index.js:265403:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

{
  "fromSubdomain": "nethermind",
  "dnpName": "nethermind.public.dappnode.eth",
  "serviceName": "nethermind.public.dappnode.eth",
  "port": 8545,
  "name": "Nethermind JSON RPC",
  "description": "JSON RPC endpoint for Nethermind Ethereum mainnet",
  "exposed": false
}
```

System info:
### Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.55
dappmanager.dnp.dappnode.eth: 0.2.50, commit: 552ab6c8
https.dnp.dappnode.eth: 0.1.3
ipfs.dnp.dappnode.eth: 0.2.16
wifi.dnp.dappnode.eth: 0.2.8
wireguard.dnp.dappnode.eth: 0.1.1
### System info
dockerComposeVersion: 1.25.5
dockerServerVersion: 20.10.12
dockerCliVersion: 20.10.12
os: debian
versionCodename: bullseye
architecture: amd64
kernel: 5.10.0-9-amd64
Disk usage: 67%

**Comment by DanieleSalatti** [comment]
Same issue here.

Will report back if I can figure out a solution.

**Comment by alexpeterson91** [comment]
fixed by https://github.com/dappnode/DAppNodePackage-nethermind/pull/83
