### ISSUE TITLE
Cosmos Package doesn't work?

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#503]
Cosmos seems to not be working and not even propagating properly.

```
Error downloading cosmos.public.dappnode.eth release from IPFS: Error validating compose file with dappnode requirements:
Error: Error downloading cosmos.public.dappnode.eth release from IPFS: Error validating compose file with dappnode requirements:

service cosmos.public.dappnode.eth has key tty that is not allowed. Allowed keys are: cap_add,cap_drop,command,depends_on,devices,entrypoint,environment,expose,extra_hosts,healthcheck,labels,logging,network_mode,networks,ports,privileged,restart,stop_grace_period,stop_signal,user,volumes,working_dir,security_opt,image,build,volumes,environment,pid,container_name,dns,ulimits,deploy
    at validateDappnodeCompose (/usr/src/app/webpack:/node_modules/@dappnode/dappnodesdk/dist/files/compose/validateDappnodeCompose.js:32:1)
    at /usr/src/app/webpack:/@dappnode/dappmanager/src/modules/release/ipfs/downloadRelease.ts:79:32
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/index.js:395467:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Error downloading cosmos.public.dappnode.eth release from IPFS: Error validating compose file with dappnode requirements:

service cosmos.public.dappnode.eth has key tty that is not allowed. Allowed keys are: cap_add,cap_drop,command,depends_on,devices,entrypoint,environment,expose,extra_hosts,healthcheck,labels,logging,network_mode,networks,ports,privileged,restart,stop_grace_period,stop_signal,user,volumes,working_dir,security_opt,image,build,volumes,environment,pid,container_name,dns,ulimits,deploy
    at http://my.dappnode/static/js/main.7777d745.js:2:10071
    at l (http://my.dappnode/static/js/main.7777d745.js:2:497403)
    at Generator._invoke (http://my.dappnode/static/js/main.7777d745.js:2:497191)
    at Generator.next (http://my.dappnode/static/js/main.7777d745.js:2:497832)
    at r (http://my.dappnode/static/js/main.7777d745.js:2:616449)
    at s (http://my.dappnode/static/js/main.7777d745.js:2:616652)
    at http://my.dappnode/static/js/main.7777d745.js:2:616711
    at new Promise (<anonymous>)
    at http://my.dappnode/static/js/main.7777d745.js:2:616592
    at p (http://my.dappnode/static/js/main.7777d745.js:2:9888)
    ```

**Comment by Pol-Lanski** [comment]
Nice! Thank you for this amazing explanation! Was the limitation of the `tty` key introduced recently? I'm trying to figure out why we had a package that used to work and now it doesn't work.

**Comment by pablomendezroyo** [comment]
To create this docker safe whitelist of keys it may not take into account the public packages, so that could be the reason why cosmos stopped working.

I have opened an issue at their repo to get to the end of this https://github.com/Colm3na/DAppNodePackage-cosmos/issues/5

**Comment by alexpeterson91** [comment]
@pablomendezroyo Any word from Colmena?

**Comment by pablomendezroyo** [comment]
Not at all
