### ISSUE TITLE
Wireguard VPN Credentials Get Link returns an error

### ISSUE THREAD

**Issue by clamdad** [dappnode/DAppNode#551]
**Describe the bug**

Clicking the `Get Link` button for Wireguard VPN credentials returns an error.

**To Reproduce**

I've reproduced this behavior on several installations using the following methods: 

- Latest release ISO on NUC, 
- Latest release ISO on HyperV
- Script Install on Ubuntu 

**Expected behavior**

The wireguard credentials should be returned.

**Screenshots**

```
Error: Error fetching credentials: Internal Server Error RequestError: getaddrinfo ENOTFOUND my.dappnode
    at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (node:_http_client:481:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at fetchWireguardConfigFile (file:///usr/src/app/packages/dappmanager/src/modules/wireguard/client.ts:86:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at WireguardClient.getDeviceCredentials (file:///usr/src/app/packages/dappmanager/src/modules/wireguard/client.ts:69:41)
    at file:///usr/src/app/packages/dappmanager/src/api/handler/index.ts:36:22
Error: Error fetching credentials: Internal Server Error RequestError: getaddrinfo ENOTFOUND my.dappnode
    at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (node:_http_client:481:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at http://dappnode.local/static/js/main.fc43bc8a.js:2:568083
    at d (http://dappnode.local/static/js/main.fc43bc8a.js:2:536844)
    at Generator.<anonymous> (http://dappnode.local/static/js/main.fc43bc8a.js:2:538187)
    at Generator.next (http://dappnode.local/static/js/main.fc43bc8a.js:2:537207)
    at n (http://dappnode.local/static/js/main.fc43bc8a.js:2:531886)
    at s (http://dappnode.local/static/js/main.fc43bc8a.js:2:532089)
    at http://dappnode.local/static/js/main.fc43bc8a.js:2:532148
    at new Promise (<anonymous>)
    at http://dappnode.local/static/js/main.fc43bc8a.js:2:532029
    at w (http://dappnode.local/static/js/main.fc43bc8a.js:2:567889)
```

**DAppNode version:**

Core DAppNode Packages versions

- bind.dnp.dappnode.eth: 0.2.6
- core.dnp.dappnode.eth: 0.2.68
- dappmanager.dnp.dappnode.eth: 0.2.63, commit: ba782a59
- https.dnp.dappnode.eth: 0.1.4
- ipfs.dnp.dappnode.eth: 0.2.19
- wifi.dnp.dappnode.eth: 0.2.8
- wireguard.dnp.dappnode.eth: 0.1.2

System info

- dockerComposeVersion: 1.29.2
- dockerServerVersion: 23.0.1
- dockerCliVersion: 23.0.1
- os: ubuntu
- versionCodename: jammy
- architecture: amd64
- kernel: 5.19.0-35-generic
- Disk usage: 6%

**Additional context**

Using `dappnode_wireguard` from the command line returns credentials, but the endpoint is blank.  I have to manually fill it with the local OP Address:

```
[Interface]
Address = xx.xx.xx.xx
PrivateKey = xxxxxxxxxxxxxxxxxxxxxxxxx
ListenPort = 51820
DNS = 172.33.1.2,xx.xx.xx.xx

[Peer]
PublicKey = xxxxxxxxxxxxxxxxxxxxxxxx
Endpoint = :51820
AllowedIPs = 172.33.0.0/16,xx.xx.xx.xx/24
```

Using `dappnode_wireguard --local` also returns an error:

```
RequestError: getaddrinfo ENOTFOUND my.dappnode
    at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (node:_http_client:481:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  code: 'ENOTFOUND',
  timings: {
    start: 1678976181467,
    socket: 1678976181467,
    lookup: 1678976181469,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1678976181469,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 2,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 2
    }
  }
}

```

**Comment by dsimog01** [comment]
Can you see your dyndns subdomain when clicking on the avatar icon on the top right corner of the Dappmanager (UI you access via http://my.dappnode). You should see something like:
```
DAppNode Identity
XXXXXXXXX
xxxxxxxxxxx.dyndns.dappnode.io
XX.XX.XX.XX (public IP)
XX.XX.XX.XX  (internal IP)
```
