### ISSUE TITLE
Connection error after updating dappnode core

### ISSUE THREAD

**Issue by johnnieskywalker** [dappnode/DAppNode#629]
I just updated dappnode core as it was suggested in dashboard an I ran into connection issue I don't know how to reconnect. My Internet connection over dappnode works but in `http://my.dappnode/#/` I see followin error 

```sh
No connection
Could not connect to DAppNode. Please make sure your VPN connection is still active. Otherwise, stop the connection and reconnect and try accessing this page again. If the problems persist, please reach us via [Discord](https://discord.gg/dappnode) or [opening a Github issue](https://github.com/dappnode/DAppNode/issues/new).
Failed to fetch
TypeError: Failed to fetch
    at http://my.dappnode/static/js/main.104290d8.js:2:714415
    at l (http://my.dappnode/static/js/main.104290d8.js:2:497860)
    at Generator._invoke (http://my.dappnode/static/js/main.104290d8.js:2:497648)
    at Generator.next (http://my.dappnode/static/js/main.104290d8.js:2:498289)
    at r (http://my.dappnode/static/js/main.104290d8.js:2:608678)
    at s (http://my.dappnode/static/js/main.104290d8.js:2:608881)
    at http://my.dappnode/static/js/main.104290d8.js:2:608940
    at new Promise (<anonymous>)
    at http://my.dappnode/static/js/main.104290d8.js:2:608821
    at Xo (http://my.dappnode/static/js/main.104290d8.js:2:714245)
    ```
    
    
![image](https://github.com/user-attachments/assets/4dabd58b-ba09-40da-aa1f-b4236e48de0c)

how can I connect back to my dappnode after the update ?

**Comment by johnnieskywalker** [comment]
In the end I connected via ssh and updated docker manually
